.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,1 +1,18 @@
 #!/bin/bash
+CURRENT_PHP_VERSION=$(update-alternatives --query php | grep 'Value:' | awk '{print $2}')
+restore_php_version() {
+  update-alternatives --set php "$CURRENT_PHP_VERSION"
+}
+trap restore_php_version EXIT
+read -p "Enter PHP version (e.g., 8.4): " PHP_VERSION
+if [ ! -f "/usr/bin/php$PHP_VERSION" ]; then
+ echo "PHP $PHP_VERSION is not found."
+fi
+update-alternatives --set php /usr/bin/php$PHP_VERSION
+rm -rf /tmp/newreli*
+cd /tmp/
+NEW_RELIC_AGENT_VERSION=$(curl -s https://download.newrelic.com/php_agent/release/ | grep -o '[1-9][0-9]\?\(\.[0-9]\+\)\{3\}' | head -n1)
+curl -o newrelic-php-agent.tar.gz https://download.newrelic.com/php_agent/release/newrelic-php5-${NEW_RELIC_AGENT_VERSION}-linux.tar.gz
+tar -xzf newrelic-php-agent.tar.gz -C /tmp/
+NR_INSTALL_USE_CP_NOT_LN=1 /tmp/newrelic-php5-$NEW_RELIC_AGENT_VERSION-linux/newrelic-install install
+sysatemctl restart php$PHP_VERSION-fpm
